name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}:latest

    permissions:
      contents: read
      packages: write  # GHCR にプッシュするために必要

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image to GHCR
        run: |
          docker push $IMAGE_NAME